name: "Test"

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        name: Test build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3
            - name: Get 8-digit SHA
              id: get_short_sha
              run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-8)" >> "$GITHUB_OUTPUT"
            - name: Test build
              uses: home-assistant/builder@master
              with:
                  args: |
                      --test \
                      --amd64 \
                      --aarch64 \
                      --target addon-shairport2-sync \
                      --docker-hub zixties60
